### ISSUE TITLE
`LICENSE`?

### ISSUE THREAD

**Issue by bcjordan** [meething/StreamSwitcher#1]
Awesome project! Have been having a lot of fun with MediaRecorder lately.

Is there a license for it?

**Comment by QVDev** [comment]
Hi @bcjordan Thanks. I am looking into the license with team and will license it properly. Once I know I come back to you. If I may ask for what kind of purpose you are using this project? Just curiosity from my side.

**Comment by QVDev** [comment]
We would like the community to contribute to this so made this an MIT license 👍 So feel free to help improve

**Comment by bcjordan** [comment]
I realized this may not come in to play since I have another layer between capture and recording (a canvas on which other stuff is drawn). Thanks for licensing though! Will let you know if it ends up coming in handy!

This is for some experiments with recording little clips of block-based coding projects, some of which can switch between interacting with video playback and camera feed(s)
