### ISSUE TITLE
Switch cameras

### ISSUE THREAD

**Issue by trackedsupport** [meething/StreamSwitcher#2]
I noticed if you switch cameras you can't go back to a camera you once had. 

So I hit record with camera A, switched to B, then switched back to A, and then the video was black and the recorder stopped.

**Comment by QVDev** [comment]
Hi @trackedsupport Thanks for opening the issue. Could you elaborate a bit more?
- Do you have multiple camera's? As at this moment that is not supported.
- Does the debug log in console gives an error?
- Are you using the demo site or do you have your own implementation? If so is there a site where I can look and debug?

When I switch from camera to screen-share and then back to camera that works for me. Maybe if you can make a video of what you bump into and be more descriptive I can help out with it.

**Comment by trackedsupport** [comment]
So I was mistaken. I saw your example and thought you were doing an interval which I didnt want but actually you were doing a timeout. So I was setting the srcObject whenever the usermedia stream was updated. 

`  var tempStream = new MediaStream();
  setTimeout(function () {
    remoteVideo.srcObject = tempStream.remoteStream;
    remoteVideo.play();
  }, 500);`


Why do I need the timeout?

It looks like it is switching cameras fine, but my video position/resolution is off now. When the camera switches from a 720p to a 1080p/4k camera, im positioned to the side of the view. Not sure what is causing that yet.

**Comment by QVDev** [comment]
The timeout is client implementation is not always needed. In this case I added this to start automatically once video is ready it can also be a button or listen to event metadata ready on the video.

So you dont need a timeout, you can replace the logic inside it with a button or listen to the right video event.

**Comment by QVDev** [comment]
The resolution change I am not sure why that is. If you do the other way around 1024 4k to 720? You still have the issue? This is not correlated to the timeout. 

But can be related on certain config to get the stream. Maybe there are maybe some settings that you need to adjust. Internally it uses peerconnection I can imagine maybe some internal renegotiation is needed to adjust to another resolution. I asume thats it but I have to see it for myself

Wish I can check this on my side though but only got one camera :). Do you adjusted the demo to fit your needs? Maybe we can get in a call and you can show me and we can debug together.

**Comment by trackedsupport** [comment]
Maybe I'm just confused. I tried a couple of tests just now and the positioning looks good. I did move the timeout code to later when they actually join the recording room but I doubt that changed it. I would have to run some tests to see if I can reproduce now. This audio and video stuff is neat but man does it feel fragile. 

Thanks for your code! 

You don't happen to know why Safari iPad the video turns to the black screen sometimes do you? It works for me until I try to record locally and remotely then it turns black. Frustrating!

**Comment by QVDev** [comment]
Thanks! I am relaying on others to find issues. Regarding safari it suppose not to work as they have not all the necesary API's implemented yet. So thats why it wont work on safari as you expect. Chrome based browser will feel way more stable try that. Also safari has different encoding than chrome with recording. I will test tomorrow on safari desktop and see if I can identify some issues.

Meanwhile you keep testing and report issues. That way we can make it more stable for everyone.

May I ask for what you are using StreamSwitcher? Than I can maybe add a "used by" section and refer to your project. 

Also feel free to make pull requests if you have some fixes or improvements.

**Comment by trackedsupport** [comment]
We are building a platform called iris.fm. 

I will let you know! I am seeing some weird timing between my voice and video - but maybe that's an issue with my computer. 

Yea Safari on the iPad seems to work right out of the box, unlike the desktop where you have to add the MediaRecorder experimental feature. I could record locally fine, record remotely fine, but not both! Could be an issue with the video conferencing library - I wrote them since I was even using the same exact media stream to test and remove other variables. Iris.fm works on Safari if you turn the exp feature on, but some people noticed issues (could be with Edge too) so I just pulled it for now. Too many things to focus on! 

Anyways thank you again!

**Comment by QVDev** [comment]
Wow I am suprised it works in safari on iPad great to hear.

Exiting project I have looked at iris.fm before cool work. 

Keep me in the loop and feel free to reach out if you need some help.

**Comment by trackedsupport** [comment]
I'll close this since I believe this was a user error.
